gsap.to('#container', {
    x:500,
    duration: 2,
    ease: 'elastic.out(1, 0.3)',
    repeat: -1,
    ease: 'power2.inOut',
    repeat: -1,
    yoyo: true,
    // yoyo: true,
    // repeat: 10,
    // delay: 1,
    // stagger: 0.5,
    // ease: 'circ.easeInOut',
    // ease: 'elastic.inOut(1, 0.3)',
    // ease: 'back.inOut(1.7, 1.5)',
    // ease: 'bounce.out',
    // ease: 'elastic.out(1, 0.3)',
    // ease: 'power2.inOut',
    // ease: 'slowMo.in(0.7, 0.7, true)',
})